backend:
  name: github
  repo: emma-neil/cooking-blog-gatsby
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: src/Images
public_folder: /Images

collections:
  - name: blog
    label: Blog
    folder: src/templates/blog-post.js
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "date", label: "Publish Date", widget: "datetime" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "featuredImage", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
